Revert "Assign the error message instead of replacing it"
This reverts commit 4dcdfb31923bfebd30e769ff0ce80e13b825b3b1.
Didn't work:

NoMethodError: undefined method `message=' for #<LoadError:0x0000555d93aa0898>
Did you mean?  message